title: A Good Cup
email: hola@rodrigo-ibarra.com
description: >- # this means to ignore newlines until "baseurl:"
  Coffe notes by Rodrigo Ibarra
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: _rodrigoibarra
github_username:  rodrigoibarra

# Build settings
markdown: kramdown
sass:
  sass_dir: _scss
  style: compressed